<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Greetings</title>
    <style>
        h1 {
            color: blue;
        }
    </style>

</head>
<body>
    This is the greetings template (Modified)
    <h1>${header}</h1>
    <p>${name}</p>
    <p>Current Date: ${currentTime}</p>
    <hr>
    <p>${footer}</p>
</body>
</html>